### PR TITLE
feat: add RabbitMQ icon

### PR DESCRIPTION
**Pull request by mthmulders**

### CODE REVIEW

**Comment by mthmulders** [comment]
I used PlantUML, using the `-encodesprite` switch, [as described by Mr. Haki](http://mrhaki.blogspot.com/2017/10/plantuml-pleasantness-creating-our-own.html). I am not aware of a font that has this icon in it.

**Comment by tupadr3** [comment]
I'll try to look into it on the weeekend

**Comment by Potherca** [comment]
_ping?_

**Comment by tupadr3** [comment]
Sorry. Been quite busy lately and haven't had the time to implement it. If you want you can implement it yourself. The source can be found at https://github.com/tupadr3/font-icon-generator.

**Comment by Potherca** [comment]
Cool, thanks! Will let you know if/when I can find the time for this.

**Pull request closed without merging**
